### PR TITLE
Redshift 7.1 Adapter: implement reconnect! like it was in 7.0

### LINKED ISSUE #19: reconnect! (called from verify!) fails with "wrong number of arguments (given 1, expected 0) (ArgumentError)"
In 7.1, reconnect! added an argument (restore_transactions: false), and according to the comments in AbstractAdapter, no longer needs to be implemented, just have a private reconnect method (which is already there).

So you might be able to simply remove the current reconnect! method for it to work.

To get the error:
```ruby
connection.disconnect!
connection.verify!
```

### PR DESCRIPTION
**Pull request by jerryclinesmith**
Closes #19

### CODE REVIEW

**Comment by jerryclinesmith** [comment]
All my tests pass, as well as running in a production environment.

**Comment by quentindemetz** [comment]
@jerryclinesmith why did you close the PR?

**Comment by jerryclinesmith** [comment]
I was still getting sporadic hard crashes, even with this change.

It's in a job using the Parallel gem, and found an issue where others reporting the same behavior, so trying to figure out if the problem is in the Redshift adapter or the parallel gem, but didn't want you to merge another change unless I was sure it was correct.

**Comment by quentindemetz** [comment]
Thanks for the explanation

**Comment by jerryclinesmith** [comment]
So the issues seemed to be with how I was using the parallel gem, and not these changes, so I'm going to reopen the pull request.

Also wanted to let you know, that I have another branch that brings the 7.1 RedshiftAdapter and DatabaseStatements fully up to date with their Postgres counterparts.  I'm still testing this branch, as the changes are extensive, but I can make another pull request later if you think you would be interested.  I've just brought in all of the latest Postgres code, but left the type maps as they were, and left out code that doesn't apply to Redshift (extensions, enum types, etc...).

**Comment by jerryclinesmith** [comment]
Going to close this, the other (better IMHO) pull request has been accepted.

**Pull request closed without merging**
