### PR TITLE
Rails 8.0 support

### PR DESCRIPTION
**Pull request by januszm**
I didn't see any major change in ActiveRecord 8 that would break this, so let's see if it'll work.

### CODE REVIEW

**Comment by quentindemetz** [comment]
Have you tried it locally at all?

**Comment by januszm** [comment]
Converting to draft

```ruby
undefined method `transform_query'
sql = transform_query(sql)
              ^^^^^^^^^^^^^^^
Did you mean?  perform_query
```

ok this was removed in 8, back to square one.
also this one removed, from the `abstract_adapter`:
```ruby
def without_prepared_statement?(binds)
```

New methods:
```ruby
      # This is meant to be implemented by the adapters that support virtual tables
      def create_virtual_table(*) # :nodoc:
      end

      # This is meant to be implemented by the adapters that support virtual tables
      def drop_virtual_table(*) # :nodoc:
      end
```

changes in
```ruby
def translate_exception_class(native_error, sql, binds)
```

and argument `statement_name` removed in 
```ruby
def log(sql, name = "SQL", binds = [], type_casted_binds = [], async: false, &block) # :doc:
```

`raw_execute` from `DatabaseStatements` that used to be wrapped with:

```ruby
def internal_execute(sql, name = "SCHEMA", allow_retry: false, materialize_transactions: true)
```

is now not wrapped and looks like:
```ruby
def raw_execute(sql, name = nil, binds = [], prepare: false, async: false, allow_retry: false, materialize_transactions: true, batch: false)
  type_casted_binds = type_casted_binds(binds)
  log(sql, name, binds, type_casted_binds, async: async) do |notification_payload|
    with_raw_connection(allow_retry: allow_retry, materialize_transactions: materialize_transactions) do |conn|
    perform_query(conn, sql, binds, type_casted_binds, prepare: prepare, notification_payload: notification_payload, batch: batch)
  end
end
```

**Comment by januszm** [comment]
With the changes above I was able to return `.all` and `where(key: value)`.

`.last` and `.find(value)` works too, as long as `self.primary_key` is set on the model

didn't test more atm

**Comment by januszm** [comment]
As a next step we could rename this by removing 7 from `activerecord7-redshift-adapter-pennylane`
add new file `redshift_8_0_adapter` and update the README, gemspec and all text content accordingly

**Comment by januszm** [comment]
@quentindemetz if you think this is something you'd accept as a PR, including the rename to just `activerecord-redshift-adapter-pennylane` (7 removed), I'll work on wrapping this up. It works in the current state - my use case does not involve "writing" and in for my project I am not going to work on verifying writes atm.

**Comment by quentindemetz** [comment]
@januszm I'm definitely willing to release the gem under a new, more appropriate name and accept your PR if it mirrors what's been done so far. We don't use redshit at work any more so I'll just have to take your word that it works 👌🏻 

Thank you for your contribution!

**Comment by januszm** [comment]
@quentindemetz if you don't use this gem at work anymore then I'm not sure if it makes sense to bother you here. This code repository is focused on specific version of Rails/ActiveRecord (7), I think I'll either release support for Rails 8 under new name, or will get back to the original : `activerecord-redshift-adapter` (I recently became a maintaner of that gem so I can update it and make a new release)

**Comment by quentindemetz** [comment]
- > @quentindemetz if you don't use this gem at work anymore then I'm not sure if it makes sense to bother you here. This code repository is focused on specific version of Rails/ActiveRecord (7), I think I'll either release support for Rails 8 under new name, or will get back to the original : `activerecord-redshift-adapter` (I recently became a maintaner of that gem so I can update it and make a new release)

I think it would be great if we didn't have to change gems every time we do a major version upgrade.

Considering you have maintainer access on `activerecord-redshift-adapter`, I'd the best path forward would be to make sure that gem supports multiple major versions of ActiveRecord. 

Feel free to draw inspiration from how this repo is organized, and even to copy all its contents to `activerecord-redshift-adapter` so that "canonical" gem can support 7.x and centralize further contributions. I can then archive this repo and update the README to say that the canonical gem now supports 7.x and even beyond. 

WDYT?

**Comment by januszm** [comment]
> I think it would be great if we didn't have to change gems every time we do a major version upgrade.

I cannot agree more. Game plan is to release this along with your original code for Rails 7 under the unified gem name `activerecord-redshift-adapter` that version follows the ActiveRecord version. I could release what you have now as 7.0.0, then add my support for 8 and release the adapter with version 8.0.0. From then we can start dropping support for older versions to avoid having monstrous if/elsif/else statements when loading the proper adapter version and ask users to match this gem's version with their current Rails/AR version. This way the "current" version of the gem will support all AR versions up to 1 full major version back. (e.g. 8.2 supports 7.2) without having to maintain too many files.

**Comment by januszm** [comment]
BTW I tested this PR in one of my production apps and it works fine at least when it comes to "reading" from Redshift.

**Comment by januszm** [comment]
Just to sum up, I think I'll close this PR without merging. Your gem name can stay unchanged as activerecord7-... I'll use my fork to release new version of the generic gem `activerecord-redshift-adapter` and already at version 8.0.0, with support for 7.0-7.2 that your team added earlier.

**Pull request closed without merging**
